from sense_hat import SenseHat

sense = SenseHat()
sense.set_rotation(180)

poken = "DAS MACHINEN IST NODT FOR GEFINGERPOKEN UND MITTENGRABBEN IST EZY FOR BREKKEN DAS SPRINGWERKS, BLOWENFUSEN MIT LOUDISH POPEN UND SPITZENSPARKEN IST NIX GEWERKEN BY DUMKOPFS! DAS RUBBERNEKKEN SITESEEREN UND STUPIDISCH VOLK BAST RELAXEN. KIPP HANDS IN POKKETS UND VATCH DAS STOFFA KUMOUDT."
sense.show_message(poken, text_colour=(255,255,0))

